layers:
- layername: /24/Concat_output_0
  nbit: 16
  observer: MinMaxObserver
  symmetry: true
  per_channel: false
  round_type: Rounding
  static: 1
- layername: /24/Reshape_1_output_0
  nbit: 16
  observer: MinMaxObserver
  symmetry: true
  per_channel: false
  round_type: Rounding
  static: 1
- layername: /24/Concat_1_output_0
  nbit: 16
  observer: MinMaxObserver
  symmetry: true
  per_channel: false
  round_type: Rounding
  static: 1
- layername: /24/Reshape_3_output_0
  nbit: 16
  observer: MinMaxObserver
  symmetry: true
  per_channel: false
  round_type: Rounding
  static: 1
- layername: /24/Concat_2_output_0
  nbit: 16
  observer: MinMaxObserver
  symmetry: true
  per_channel: false
  round_type: Rounding
  static: 1
- layername: /24/Reshape_5_output_0
  nbit: 16
  observer: MinMaxObserver
  symmetry: true
  per_channel: false
  round_type: Rounding
  static: 1
- layername: '457'
  nbit: 16
  observer: MinMaxObserver
  symmetry: true
  per_channel: false
  round_type: Rounding
  static: 1
