model:
  onnx_model: modes/demo/model/yolov5s.onnx

work_mode: PTQ

quant:
  activation:
    observer: MinMaxObserver
    dtype: int8
    symmetry: True
  weight:
    observer: MinMaxObserver
    dtype: int8
    symmetry: True
    per_channel: True

dataset:
  calibrate:
    root: modes/demo/datasets/calibration/images
    calibrate_num_sampler: 20
    batch_size: 1
    num_worker: 4
  transform:
    resize: [640, 640]
    crop: [640, 640]
    mean: [0.0, 0.0, 0.0]
    std: [1.0, 1.0, 1.0]

out_dir: modes/demo/outputs/quant/
