model:
  onnx_model: modes/basketball/outputs/quant/yolov8n_detect_sperson_ball_hoop_ballhoop_h1024_w3328_20260720-2_best_opset13_fp32_raw_deploy_model.onnx
  quant_param: modes/basketball/outputs/quant/yolov8n_detect_sperson_ball_hoop_ballhoop_h1024_w3328_20260720-2_best_opset13_fp32_raw_quant_param.yaml

work_mode: Metric

dataset:
  eval:
    type: Custom
    loader: common/evaluation/coco_loader.py
    parameters:
      ann_file: modes/basketball/datasets/evaluation/annotations/instances.json
      img_dir: modes/basketball/datasets/evaluation/images
      normalize_mean: [0.0, 0.0, 0.0]
      normalize_std: [1.0, 1.0, 1.0]
      resize_size: [1024, 3328]
      crop_size: [1024, 3328]
      num_samples: 0
      batch_size: 1
      num_workers: 4

metric:
  type: extern_python
  source: common/evaluation/yolo_coco_metric.py
  parameters:
    annfile: modes/basketball/datasets/evaluation/annotations/instances.json
    img_size: [1024, 3328]
    decode_mode: yolov8_raw
    conf_threshold: 0.25
    iou_threshold: 0.7
    img_dir: modes/basketball/datasets/evaluation/images
    vis_dir: modes/basketball/outputs/evaluation/visualizations
    vis_num: 20
    vis_conf_threshold: 0.25
    vis_max_boxes: 100
  result_file: metric_result.csv

out_dir: modes/basketball/outputs/evaluation
