layers:
- layername: input_tensor.11
  nbit: 16
  observer: MinMaxObserver
  symmetry: true
  per_channel: false
  round_type: None
  static: 1
- layername: onnx::Concat_428
  nbit: 16
  observer: MinMaxObserver
  symmetry: true
  per_channel: false
  round_type: None
  static: 1
- layername: input_tensor.19
  nbit: 16
  observer: MinMaxObserver
  symmetry: true
  per_channel: false
  round_type: None
  static: 1
- layername: onnx::Concat_443
  nbit: 16
  observer: MinMaxObserver
  symmetry: true
  per_channel: false
  round_type: None
  static: 1
- layername: input_tensor.27
  nbit: 16
  observer: MinMaxObserver
  symmetry: true
  per_channel: false
  round_type: None
  static: 1
- layername: onnx::Concat_458
  nbit: 16
  observer: MinMaxObserver
  symmetry: true
  per_channel: false
  round_type: None
  static: 1
- layername: '459'
  nbit: 16
  observer: MinMaxObserver
  symmetry: true
  per_channel: false
  round_type: None
  static: 1
