model:
  onnx_model: modes/basketball/model/yolov8n_detect_sperson_ball_hoop_ballhoop_h1920_w1920_20260720-2_best.onnx

work_mode: PTQ

quant:
  activation:
    observer: MinMaxObserver
    dtype: int8
    symmetry: True
  weight:
    observer: MinMaxObserver
    dtype: int8
    symmetry: True
    per_channel: True

dataset:
  calibrate:
    root: modes/soccer/datasets/calibration/images
    calibrate_num_sampler: 20
    batch_size: 1
    num_worker: 1
  transform:
    resize: [1024, 3328]
    crop: [1024, 3328]
    mean: [0.0, 0.0, 0.0]
    std: [1.0, 1.0, 1.0]

out_dir: modes/basketball/outputs/quant/
