model:
  onnx_model: modes/soccer/model/yolov8n_detect-auxHM-seq-stack-3f_sperson_ball_goal_h3328_w3328_20260825_best_3input.onnx
  input_count: 3

target_platform: rk3576
do_quantization: true

quant:
  dtype: w8a8
  algorithm: normal
  method: channel
  hybrid_level: 0
  auto_hybrid: false

build:
  optimization_level: 3
  float_dtype: float16

dataset:
  root: modes/soccer/datasets/calibration
  sample_count: 14
  sequence_length: 3
  frame_step: 1

preprocess:
  mean: [0.0, 0.0, 0.0]
  std: [1.0, 1.0, 1.0]
