model: modes/demo_v5/outputs/compile/rk3576/demo_v5_rk3576.rknn
build_config: modes/demo_v5/configs/rk3576/rknn.yaml

runtime:
  target: null
  device_id: null
  verbose: false
  perf_debug: false
  eval_mem: false

dataset:
  ann_file: modes/basketball/datasets/evaluation/annotations/instances.json
  img_dir: modes/basketball/datasets/evaluation/images
  input_size: [704, 1280]
  color_order: RGB
  num_samples: 0

decode:
  mode: yolov5_headcut
  conf_threshold: 0.25
  iou_threshold: 0.7
  anchors:
    - [10, 13, 16, 30, 33, 23]
    - [30, 61, 62, 45, 59, 119]
    - [116, 90, 156, 198, 373, 326]
  class_map: {0: 1, 1: 2, 2: 3, 3: 4}

output:
  result_file: modes/demo_v5/outputs/evaluation/rk3576/metric_result.csv
  predictions_file: modes/demo_v5/outputs/evaluation/rk3576/predictions.json
  vis_dir: modes/demo_v5/outputs/evaluation/rk3576/visualizations
  vis_num: 20
  vis_conf_threshold: 0.25
  vis_max_boxes: 100
