model:
  onnx_model: modes/demo_v8/outputs/quant/yolo11n_opset13_fp32_deploy_model.onnx
  quant_param: modes/demo_v8/outputs/quant/yolo11n_opset13_fp32_quant_param.yaml

work_mode: Compare

dataset:
  transform:
    source: compose
    args: "[transforms.Resize([960, 960]), transforms.CenterCrop([960, 960]), transforms.ToTensor(), transforms.Normalize([0.0, 0.0, 0.0], [1.0, 1.0, 1.0])]"

Compare:
  input_file: modes/soccer/datasets/evaluation/images/clip-0_frame-1000.jpg
  result_file: layer_compare.csv
  layer_dump: false

analysis_cfg:
  sim_compare: true

out_dir: modes/demo_v8/outputs/evaluation/compare
